name: smart_sheet
description: تطبيق لإدارة خطوط إنتاج مصانع الكرتون - Smart Sheet
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # تخزين محلي سريع
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # إدارة الحالة
  provider: ^6.1.2

  # اختيار الصور والكاميرا
  image: ^4.1.7

  # إنشاء ملفات PDF
  pdf: ^3.10.0
  printing: ^5.14.2

  # رسوم متحركة
  lottie: ^2.7.0

  # تخزين الإعدادات
  shared_preferences: ^2.2.2

  # للتعامل مع المسارات
  path: ^1.8.3

  # ZIP للنسخة الاحتياطية
  archive: ^3.5.1

  # فتح الروابط
  url_launcher: ^6.3.2

  # تحسين UI
  flutter_screenutil: ^5.9.3

  # إعدادات إضافية
  rename: ^3.1.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  math_expressions: ^3.0.0
  change_app_package_name: ^1.5.0
  device_info_plus: ^12.3.0
  open_file: ^3.5.10
  file_picker: ^10.3.7
  supabase_flutter: ^2.12.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0
  flutter_foreground_task: ^9.1.0
  flutter_native_contact_picker: ^0.0.11
  arabic_reshaper: ^0.0.1
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0
  qr_flutter: ^4.1.0
  uuid: ^4.3.3

  window_manager: ^0.5.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: 2.4.13
  # إضافة حزمة الأيقونات
  flutter_launcher_icons: ^0.13.1

# إعدادات توليد الأيقونات باستخدام الاسم الجديد app_icon.jpg
flutter_launcher_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/images/app_icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.jpg"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700